### ISSUE TITLE
[DS202] Change Step 3 of W02 lab roadmap

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds202-course-notes#123]
Rethink Step 3:

- [ ] Load ISLR2 package
- [ ] View(Auto)
- [ ] write auto to csv
- [ ] load auto back from csv

**Comment by mc-o** [comment]
Edited - this refers to W02 lab not W03
