### ISSUE TITLE
[DS202] Change Step 2 of W02 lab roadmap

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds202-course-notes#124]
Add ggplot

- [x] After plot instructions, add ggplot code
- [x] Briefly explain what a dataframe is
- [x] Revise the time

**Comment by jonjoncardoso** [comment]
I edited the title - this actually refers to W02 lab not W03

**Comment by jonjoncardoso** [comment]
Closes in #126
