### ISSUE TITLE
[DS202] Create roadmap for W02 lab

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds202-course-notes#40]
In the first lab of DS202, we want to do some basic exploratory data analysis using R while solving any questions that students might have about R. 

Ideally, students would come with a basic background in R, then we would focus mostly on the Applied exercises at the end of Section 2.4 of the **ISLRv2 book** (our official textbook).

> <span>Gareth James et al., <i>An Introduction to Statistical Learning: With Applications in R</i>, Second edition., Springer texts in statistics (New York NY: Springer, 2021), https://www.statlearning.com/.</span>

## A survey

To inform us of what to recap on the first lab, let's create a survey to hand to students on Week 01.

- [x] Edit the MS form available on [this link](https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=_epnVXfnpUKRu5RA_UO4kxSRjeLM9-hAoQ9qhOe5Jr1UQVZQWkZXVUdBN0RLUVJKUVBMQzRBQ09YNyQlQCN0PWcu&Token=95d139c1b78e461f931739e152de87b1)
- [ ] Ask students which class group they are enrolled in (there will be four classes)
- [ ] Create questions that would help us gauge how much of Section 2.3 we should cover in our lab.

## Lab Roadmap
- [x] Open a git branch from `develop` and name it `issue<number-of-this-issue>-<your-github-username>-roadmap-w02-lab`
- [x] Create a webpage for DS202 - W02 lab. This should have the same format as [DS105 - W02 lab](https://lse-dsi.github.io/lse-ds105-course-notes/weeks/week02/lab.html). You can check the source code [here](https://github.com/LSE-DSI/lse-ds105-course-notes/blob/main/weeks/week02/lab.qmd)

Lay out a lab roadmap we can all use in our own individual classes:
- [x] Allocate time for an R recap
- [x] Allocate some time for the Applied Exercises of Section 2.4
- [x] Decide whether it's worth dedicating time for the Conceptual Exercises of Section 2.4

## Complete the task

- [ ] Once you have finished, open a Pull Request from the git branch you created to `develop`. Tag @jonjoncardoso as a reviewer

**Comment by jonjoncardoso** [comment]
Note: I have already downloaded the original R notebooks that are used in the book. I've placed them under [lse-ds202-course-notes](https://github.com/LSE-DSI/lse-ds202-course-notes)/[resources](https://github.com/LSE-DSI/lse-ds202-course-notes/tree/main/resources)/[ISLR2](https://github.com/LSE-DSI/lse-ds202-course-notes/tree/main/resources/ISLR2)/[Rmarkdown_Notebooks](https://github.com/LSE-DSI/lse-ds202-course-notes/tree/main/resources/ISLR2/Rmarkdown_Notebooks)/

**Comment by mangoJ0106** [comment]
Thanks, Jon! That is very helpful.

**Comment by jonjoncardoso** [comment]
@mangoJ0106 the way I pre-curated the list of exercises from the book of the following lab might help you:

https://github.com/LSE-DSI/lse-ds202-course-notes/issues/52
